# Generated by Django 5.2.7 on 2026-02-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='users',
        ),
    ]
