# Generated by Django 5.2.7 on 2026-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_game_agent_alter_game_patient_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=64, unique=True),
        ),
    ]
