# Generated by Django 5.2.7 on 2026-02-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_league_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='invite_code',
        ),
    ]
