# Generated by Django 5.2.7 on 2026-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_remove_league_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=64, unique=True),
        ),
    ]
