# Generated by Django 5.2.7 on 2026-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_alter_league_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(max_length=64),
        ),
    ]
