# Generated by Django 5.2.7 on 2026-02-16 20:06

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_league_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
