# Generated by Django 5.2.7 on 2026-02-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_game_league_league_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league', to='league.league'),
        ),
    ]
