# Generated by Django 5.2.7 on 2026-02-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_alter_game_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='league',
        ),
        migrations.AddField(
            model_name='league',
            name='games',
            field=models.ManyToManyField(related_name='game', to='league.game'),
        ),
    ]
