# Generated by Django 5.2.7 on 2026-02-13 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_game_patient_alter_game_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='password_hash',
        ),
    ]
